### ISSUE TITLE
[Discussion] Barrel Textures and Sounds

### ISSUE THREAD

**Issue by Pyromanc3r** [VintageModsReforged/VintageBarrels#2]
> This looks too dark to me

I was just liking the idea of dark wood. :) 
Try this variant 
[barrels.zip](https://github.com/user-attachments/files/18156450/barrels.zip)

Side view:
![side](https://github.com/user-attachments/assets/1dacefcb-0798-42d0-bbd5-142d9a0a68c6)

Upper side. Stacking one type:
![v1-1](https://github.com/user-attachments/assets/907f99cb-481a-45e1-a354-bb8a12b18cf4)

Upper side. Different types:
![v1-2](https://github.com/user-attachments/assets/819a5266-599e-4589-8113-91e79307055d)

Upper side. Alternative variant:
![v2](https://github.com/user-attachments/assets/d854b2e2-2c54-4ad6-b307-9f317bc9fa96)

I'm not sure about the top cover though, I think in this case it becomes like a pull-out drawer. With this version it might be worth moving the position of the wood labels a bit lower by 1 pixel so that it doesn't overlap the handle.

upd: I see you've already updated the textures yourself. Oh well...

**Comment by CrossVas** [comment]
If you could also make an `opened/active` variant, I'll include these into the mod, with fixes for Wooden label.
Here is the format. I just need the `active` front.
![image](https://github.com/user-attachments/assets/3b05b21e-78f9-4b86-8f7e-c25cf321daa3)

**Comment by CrossVas** [comment]
![image](https://github.com/user-attachments/assets/8b7c91ee-cba4-42e8-9369-3121af536675)
IDK, I'll let you come up with something better maybe :d
I visualize the active front as a barrel without the lid, a bit darker and empty.

**Comment by Pyromanc3r** [comment]
I see this as a simple solution. I'm not sure about the colour scheme though, but it looks good to me.

Version 1
![2024-12-17_21 41 31](https://github.com/user-attachments/assets/c53ad92c-4d3e-492d-8b1a-1ba36a50bdea)
![2024-12-17_21 41 35](https://github.com/user-attachments/assets/5060d610-8303-4880-882c-53ab11cd0b98)


Version 2.
![2024-12-17_21 46 17](https://github.com/user-attachments/assets/d70a68d0-744d-4e96-a363-684c07e14b41)
![2024-12-17_21 46 21](https://github.com/user-attachments/assets/302769f2-7a1f-4314-857e-1d405fb51dd4)

![copper1](https://github.com/user-attachments/assets/9757d6b9-a12b-428c-afcc-bc683dff2191)
![copper2](https://github.com/user-attachments/assets/51e4acb4-d449-4853-8557-9d392d2864a1)


I personally like version 2 better
I don't know the best way to make a crystal barrel yet. Semi-transparency is not supported by blocks, right? I think it would look good to display the contents inside the crystal barrel when it is opened. Then a semi-transparent lid could be used.


I also thought it would be nice to add some new sounds. I found some audio samples, maybe some of these will be useful.
These two I've edited a bit. 
[sounds.zip](https://github.com/user-attachments/files/18170330/sounds.zip)



They were downloaded from here http://foto.teoteater.ee/muusika/1001%20Sound%20Effects//Doors%20&%20Drawers/
I used this service https://www.findsounds.com/

**Comment by CrossVas** [comment]
1. Yeah, second variant looks better imo.

> Semi-transparency is not supported by blocks, right?
2. I'm new to OpenGL and minecraft renderers in general, so yeah, for now, semi-transparent textures are a pain for me to render `properly`.
3. About sounds. Eh, both vanilla and your variant rely on `sliding effect` which is not appropriate for this `hinge lid (?)` concept.
I'll add a config that will decide which sounds to use. For now, it's vanilla barrel sounds and this: 
https://freesound.org/people/IENBA/sounds/607911/

**Comment by Pyromanc3r** [comment]
I think your version of the sound is actually better. 

Finished the textures. I hope this is the final version, but you can edit it if you think you need to.
[new.zip](https://github.com/user-attachments/files/18190817/new.zip)
